version: "3"
services:
    mysql_master:
        image: mysql:5.7.27
        hostname: ${MASTER_HOSTNAME}
        volumes:
            - ./master/etc/mysql/conf.d:/etc/mysql/conf.d:ro
            - ./master/user/share/zoneinfo/:/usr/share/zoneinfo:ro
            - ./master/var/lib/mysql:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: ${MASTER_ROOT_PASSWORD}
        networks:
            replication_network:
                ipv4_address: ${MASTER_HOST_IP}
    mysql_slave:
        image: mysql:5.7.27
        hostname: ${SLAVE_HOSTNAME}
        volumes:
            - ./slave/etc/mysql/conf.d:/etc/mysql/conf.d:ro
            - ./slave/user/share/zoneinfo/:/usr/share/zoneinfo:ro
            - ./slave/var/lib/mysql:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: ${SLAVE_ROOT_PASSWORD}
        depends_on:
            - ${MASTER_HOSTNAME}
        networks:
            replication_network:
                ipv4_address: ${SLAVE_HOST_IP}
    replication:
        image: ubuntu:18.04
        volumes:
            - ./scripts:/opt/scripts
        depends_on:
            - ${MASTER_HOSTNAME}
            - ${SLAVE_HOSTNAME}
        networks:
            - replication_network
        environment:
            MASTER_HOSTNAME: ${MASTER_HOSTNAME}
            MASTER_HOST_IP: ${MASTER_HOST_IP}
            MASTER_ROOT_USER: ${MASTER_ROOT_USER}
            MASTER_ROOT_PASSWORD: ${MASTER_ROOT_PASSWORD}

            SLAVE_HOSTNAME: ${SLAVE_HOSTNAME}
            SLAVE_HOST_IP: ${SLAVE_HOST_IP}
            SLAVE_ROOT_USER: ${SLAVE_ROOT_USER}
            SLAVE_ROOT_PASSWORD: ${SLAVE_ROOT_PASSWORD}

            SLAVE_REPL_USER: ${SLAVE_REPL_USER}
            SLAVE_REPL_PASSWORD: ${SLAVE_REPL_PASSWORD}
        command: bash /opt/scripts/mysql-setup-replication.sh
networks:
    replication_network:
        ipam:
            config:
                - subnet: 10.208.0.0/16
