version: "3"
services:
    master_1:
        extends:
            file: common-services.yml
            service: common_master_1
    slave_1:
        extends:
            file: common-services.yml
            service: common_slave_1
        depends_on:
            - ${MASTER_1_HOSTNAME}
    replication:
        extends:
            file: common-service.yml
            service: replication
        depends_on:
            - ${MASTER_1_HOSTNAME}
            - ${SLAVE_1_HOSTNAME}
        command: bash ${REPL_SCRIPT_MOUNT_PATH}/master-2-slave.sh
    pma:
        depends_on:
            - ${MASTER_1_HOSTNAME}
            - ${SLAVE_1_HOSTNAME}
            - replication
