version: "3"
services:
    mysql_master_1:
        image: mysql:5.7.27
        hostname: ${MASTER_1_HOSTNAME}
        volumes:
            - ./master/etc/mysql/conf.d/master1.cnf:/etc/mysql/conf.d/my.cnf:ro
            - ./master/user/share/zoneinfo/:/usr/share/zoneinfo:ro
            - ./master/var/lib/mysql/master1:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: ${MASTER_1_ROOT_PASSWORD}
        networks:
            replication_network:
                ipv4_address: ${MASTER_1_HOST_IP}
    mysql_master_2:
        image: mysql:5.7.27
        hostname: ${MASTER_2_HOSTNAME}
        volumes:
            - ./master/etc/mysql/conf.d/master2:/etc/mysql/conf.d/my.cnf:ro
            - ./master/user/share/zoneinfo/:/usr/share/zoneinfo:ro
            - ./master/var/lib/mysql/master2:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: ${MASTER_2_ROOT_PASSWORD}
        networks:
            replication_network:
                ipv4_address: ${MASTER_2_HOST_IP}
    replication:
        image: ubuntu:18.04
        volumes:
            - ./scripts:/opt/scripts
        depends_on:
            - ${MASTER_HOSTNAME}
            - ${SLAVE_HOSTNAME}
        networks:
            - replication_network
        environment:
            MASTER_1_HOSTNAME: ${MASTER_1_HOSTNAME}
            MASTER_1_HOST_IP: ${MASTER_1_HOST_IP}
            MASTER_1_ROOT_USER: ${MASTER_1_ROOT_USER}
            MASTER_1_ROOT_PASSWORD: ${MASTER_1_ROOT_PASSWORD}

            MASTER_2_HOSTNAME: ${MASTER_2_HOSTNAME}
            MASTER_2_HOST_IP: ${MASTER_2_HOST_IP}
            MASTER_2_ROOT_USER: ${MASTER_2_ROOT_USER}
            MASTER_2_ROOT_PASSWORD: ${MASTER_2_ROOT_PASSWORD}
        command: bash /opt/scripts/master-2-master.sh
networks:
    replication_network:
        ipam:
            config:
                - subnet: 10.208.0.0/16
