version: "3"
services:
    master_1:
        image: mysql:5.7.27
        container_name: ${MASTER_1_HOSTNAME}
        hostname: ${MASTER_1_HOSTNAME}
        volumes:
            - ../conf/master1.cnf:/etc/mysql/conf.d/my.cnf:ro
            - ../data/master1:/var/lib/mysql:rw
            - /usr/share/zoneinfo/:/usr/share/zoneinfo/:ro
        environment:
            MYSQL_ROOT_PASSWORD: ${MASTER_1_ROOT_PASSWORD}
        networks:
            replication_network:
                ipv4_address: ${MASTER_1_HOST_IP}
    master_2:
        image: mysql:5.7.27
        container_name: ${MASTER_2_HOSTNAME}
        hostname: ${MASTER_2_HOSTNAME}
        volumes:
            - ../conf/master2.cnf:/etc/mysql/conf.d/my.cnf:ro
            - ../data/master2:/var/lib/mysql:rw
            - /usr/share/zoneinfo/:/usr/share/zoneinfo/:ro
        environment:
            MYSQL_ROOT_PASSWORD: ${MASTER_2_ROOT_PASSWORD}
        networks:
            replication_network:
                ipv4_address: ${MASTER_2_HOST_IP}
    replication:
        image: ubuntu:18.04
        volumes:
            - ../scripts:${REPL_SCRIPT_MOUNT_PATH}
        depends_on:
            - ${MASTER_1_HOSTNAME}
            - ${MASTER_2_HOSTNAME}
        networks:
            - replication_network
        environment:
            MASTER_1_HOSTNAME: ${MASTER_1_HOSTNAME}
            MASTER_1_HOST_IP: ${MASTER_1_HOST_IP}
            MASTER_1_ROOT_USER: ${MASTER_1_ROOT_USER}
            MASTER_1_ROOT_PASSWORD: ${MASTER_1_ROOT_PASSWORD}

            MASTER_2_HOSTNAME: ${MASTER_2_HOSTNAME}
            MASTER_2_HOST_IP: ${MASTER_2_HOST_IP}
            MASTER_2_ROOT_USER: ${MASTER_2_ROOT_USER}
            MASTER_2_ROOT_PASSWORD: ${MASTER_2_ROOT_PASSWORD}

            REPL_USER: ${REPL_USER}
            REPL_PASSWORD: ${REPL_PASSWORD}
        command: bash ${REPL_SCRIPT_MOUNT_PATH}/master-2-master.sh
networks:
    replication_network:
        ipam:
            config:
                - subnet: 10.208.0.0/16
